/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as MyListRouteImport } from './routes/my-list'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TitleTypeIdRouteImport } from './routes/title.$type.$id'
import { Route as WatchTypeIdRouteImport } from './routes/watch.$type.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListRoute = MyListRouteImport.update({
  id: '/my-list',
  path: '/my-list',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TitleTypeIdRoute = TitleTypeIdRouteImport.update({
  id: '/title/$type/$id',
  path: '/title/$type/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchTypeIdRoute = WatchTypeIdRouteImport.update({
  id: '/watch/$type/$id',
  path: '/watch/$type/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/history': typeof HistoryRoute
  '/my-list': typeof MyListRoute
  '/search': typeof SearchRoute
  '/title/$type/$id': typeof TitleTypeIdRoute
  '/watch/$type/$id': typeof WatchTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/history': typeof HistoryRoute
  '/my-list': typeof MyListRoute
  '/search': typeof SearchRoute
  '/title/$type/$id': typeof TitleTypeIdRoute
  '/watch/$type/$id': typeof WatchTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/history': typeof HistoryRoute
  '/my-list': typeof MyListRoute
  '/search': typeof SearchRoute
  '/title/$type/$id': typeof TitleTypeIdRoute
  '/watch/$type/$id': typeof WatchTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/history'
    | '/my-list'
    | '/search'
    | '/title/$type/$id'
    | '/watch/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/history'
    | '/my-list'
    | '/search'
    | '/title/$type/$id'
    | '/watch/$type/$id'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/history'
    | '/my-list'
    | '/search'
    | '/title/$type/$id'
    | '/watch/$type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  HistoryRoute: typeof HistoryRoute
  MyListRoute: typeof MyListRoute
  SearchRoute: typeof SearchRoute
  TitleTypeIdRoute: typeof TitleTypeIdRoute
  WatchTypeIdRoute: typeof WatchTypeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-list': {
      id: '/my-list'
      path: '/my-list'
      fullPath: '/my-list'
      preLoaderRoute: typeof MyListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/title/$type/$id': {
      id: '/title/$type/$id'
      path: '/title/$type/$id'
      fullPath: '/title/$type/$id'
      preLoaderRoute: typeof TitleTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$type/$id': {
      id: '/watch/$type/$id'
      path: '/watch/$type/$id'
      fullPath: '/watch/$type/$id'
      preLoaderRoute: typeof WatchTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  HistoryRoute: HistoryRoute,
  MyListRoute: MyListRoute,
  SearchRoute: SearchRoute,
  TitleTypeIdRoute: TitleTypeIdRoute,
  WatchTypeIdRoute: WatchTypeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
